### ISSUE TITLE
questões de resposta livre, escondidas para o publico

### ISSUE THREAD

**Issue by miguel-marques** [gomadevelopment/webapp-macau#51]
Ao falar com o cliente, surgiu o tema de que questões que usem resposta livre, possam ser publicadas para o publico (fora da turma), se as mesmas forem ocultadas, uma vez que não há forma de o professor corrigir.
Depois digam se tal é possivel

Thx

**Comment by pgomes99** [comment]
Isso não fez sentido nenhum...é melhor falarmos nisso logo

**Comment by miguel-marques** [comment]
lol, ok!
